# Generated by Django 4.2.30 on 2026-07-01 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English (Latin)'), ('hi', 'Hindi (Devanagari)'), ('sa', 'Sanskrit (Devanagari)')], default='en', max_length=2)),
                ('style', models.CharField(choices=[('en_casual', 'English - Casual'), ('en_formal', 'English - Formal'), ('en_cursive', 'English - Cursive'), ('hi_devanagari', 'Hindi - Devanagari Standard'), ('hi_cursive', 'Hindi - Cursive Devanagari'), ('sa_devanagari', 'Sanskrit - Devanagari Standard'), ('sa_vedic', 'Sanskrit - Vedic Style')], default='en_casual', max_length=20)),
                ('output_format', models.CharField(choices=[('png', 'PNG'), ('pdf', 'PDF'), ('both', 'Both PNG & PDF')], default='both', max_length=4)),
                ('page_size', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('LETTER', 'Letter (8.5 x 11 in)'), ('A5', 'A5 (148 x 210 mm)'), ('CUSTOM', 'Custom')], default='A4', max_length=10)),
                ('custom_width', models.FloatField(blank=True, help_text='Custom width in mm', null=True)),
                ('custom_height', models.FloatField(blank=True, help_text='Custom height in mm', null=True)),
                ('margin_top', models.FloatField(default=20, help_text='Top margin in mm')),
                ('margin_bottom', models.FloatField(default=20, help_text='Bottom margin in mm')),
                ('margin_left', models.FloatField(default=20, help_text='Left margin in mm')),
                ('margin_right', models.FloatField(default=20, help_text='Right margin in mm')),
                ('line_spacing', models.FloatField(default=1.5, help_text='Line spacing multiplier')),
                ('font_size', models.FloatField(default=14, help_text='Font size in pt')),
                ('ink_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('paper_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('line_variance', models.FloatField(default=0.3, help_text='Line position variance (0-1)')),
                ('word_spacing', models.FloatField(default=1.0, help_text='Word spacing multiplier')),
                ('char_spacing', models.FloatField(default=1.0, help_text='Character spacing multiplier')),
                ('slant', models.FloatField(default=0.0, help_text='Slant angle in degrees')),
                ('pressure_variance', models.FloatField(default=0.3, help_text='Pressure variance (0-1)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output_png', models.FileField(blank=True, null=True, upload_to='handwritten/')),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to='handwritten/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
