# Generated by Django 4.2.30 on 2026-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='style',
        ),
        migrations.AddField(
            model_name='conversion',
            name='custom_font',
            field=models.FileField(blank=True, help_text='Upload a .ttf font file for custom handwriting', null=True, upload_to='custom_fonts/'),
        ),
    ]
