# Generated by Django 4.2.30 on 2026-07-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handwriting_app', '0002_remove_conversion_style_conversion_custom_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='custom_font',
        ),
    ]
